### ISSUE TITLE
Add section for adding figures with custom size using laTex

### ISSUE THREAD

**Issue by mrandrewandrade** [softcover/softcover_book#6]
Hey Michael,
I was playing around with adding figures using just latex in the markdown file, and I found a good method for custom sized images:
```latex
\begin{figure}[h!]
\centering
\includegraphics[width=50mm,scale=0.5]{images/example.pdf} 
\caption{Inserting figure using only laTex}
\label{fig:custom_fig_label}
\end{figure}
```
Do you want me to send you a PR with this code as an example?  I could add it as a section after [4.2.5 Advanced figure placement](http://manual.softcover.io/book/customization#sec-advanced_figure_placement)

**Comment by mhartl** [comment]
Thanks for the note. You can make a PR. Make sure to typeset things like
LaTeX correctly (e.g., \LaTeX, not laTex or latex). Also, it's Markdown,
not markdown. Finally, captions should always end with a period.

2015-09-03 10:23 GMT-07:00 Andrew Andrade <notifications@github.com>:

> Hey Michael,
> I was playing around with adding figures using just latex in the markdown
> file, and I found a good method for custom sized images:
>
> \begin{figure}[h!]\centering\includegraphics[width=50mm,scale=0.5]{images/example.pdf} \caption{Inserting figure using only laTex}\label{fig:method}\end{figure}
>
> Do you want me to send you a PR with this code as an example? I could add
> it as a section after 4.2.5 Advanced figure placement
> <http://manual.softcover.io/book/customization#sec-advanced_figure_placement>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/softcover/softcover_book/issues/6>.
>



-- 
Michael Hartl
Author, Rails Tutorial <http://www.railstutorial.org/>
Founder, Softcover <http://www.softcover.io/>

**Comment by mrandrewandrade** [comment]
Thanks for the feedback. Please find the PR [here](https://github.com/softcover/softcover_book/pull/7)

**Comment by mrandrewandrade** [comment]
@mhartl  so PR https://github.com/softcover/softcover_book/pull/7 solves the problem for pdf but it does not work for html/epub/mobi

Any suggestions on how to change the size of images?  It could be doe through css but seems very mundane.

**Comment by mhartl** [comment]
Right, that's probably why it's not in the manual. Because PDF comes
directly from LaTeX, which supports basically everything, but
HTML/EPUB/MOBI comes from a custom system, this sort of "It works in PDF
but not the others" happens all the time. It's just a restriction you have
to write around.

Given the amount of work involved in adding support for this feature to the
HTML pipeline, I'm inclined to give it amiss at this point. Nevertheless,
I'd like to thank you for your efforts.

2015-09-03 11:38 GMT-07:00 Andrew Andrade <notifications@github.com>:

> @mhartl <https://github.com/mhartl> so PR #7
> <https://github.com/softcover/softcover_book/pull/7> solves the problem
> for pdf but it does not work for html/epub/mobi
>
> Any suggestions on how to change the size of images? It could be doe
> through css but seems very mundane.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/softcover/softcover_book/issues/6#issuecomment-137537736>
> .
>



-- 
Michael Hartl
Author, Rails Tutorial <http://www.railstutorial.org/>
Founder, Softcover <http://www.softcover.io/>

**Comment by mrandrewandrade** [comment]
@mhartl this is a side question I couldn't find the answer to in the manual.

Is there a way which you can deploy the autogenerated html/mobi/epub and a custom LaTex/PolyTex generated pdf to the platform? 

I see myself completing the book in markdown and using the autogenerated html/mobi/epub.  For the pdf version, I plan to do a bunch of customization in PolyTex which would be different than the epub and mobi version. 

Is there a way to currently do this?

**Comment by mrandrewandrade** [comment]
As it when I run sc deploy it would build the epub/mobi version but also would include a custom pdf which is already generated?

Given the "It works in PDF but not the others", it would be pretty useful, since I see most people reading the pdf version of my book

**Comment by mhartl** [comment]
If you're willing to drop HTML/EPUB/MOBI support, you can [customize](http://manual.softcover.io/book/customization#sec-customizing_deploys) your `.softcover-deploy` file to suppress them:
```
softcover build:pdf
softcover publish
```
The site assumes the existence of an HTML version, though, and I'm not sure what happens if it isn't there.
