### ISSUE TITLE
Wrong equation numbers when building HTML locally

### ISSUE THREAD

**Issue by asmaier** [softcover/softcover_book#8]
I'm using Mac OS X 10.10.4. I cloned the repository of the softcover book and ran

    softcover server

to build and serve the HTML files. But when doing so, the equation numbering seems to be messed up. Online at http://manual.softcover.io/book/softcover_markdown#eq-golden_ratio it looks ok and the equation number is (3.1) as expected: 

![softcover_markdown_online](https://cloud.githubusercontent.com/assets/3169297/9886884/e7b3a260-5bec-11e5-8e00-0b9ea0538a9c.jpg)

But offline at `http://localhost:4000/softcover_markdown#eq-golden_ratio` I see instead the number (1):

![softcover_markdown_server](https://cloud.githubusercontent.com/assets/3169297/9886947/58832326-5bed-11e5-8785-cbfef955e553.jpg)

When I open the html file `softcover_book/html/softcover_book.html#eq-golden_ratio` I see the number (2):

![softcover_book](https://cloud.githubusercontent.com/assets/3169297/9887036/cec4e4c0-5bed-11e5-8829-d1fa56bd746d.jpg)

And most confusingly when I open the html file `softcover_book/html/softcover_markdown.html#eq-golden_ratio` I see (3.adfadsfa  1):

![softcover_markdown](https://cloud.githubusercontent.com/assets/3169297/9887077/12545ea0-5bee-11e5-858c-11fc8c4469d1.jpg)

What could be wrong with my setup?

**Comment by mhartl** [comment]
Upgrade to the latest gem:
```
$ gem update softcover
```

**Comment by asmaier** [comment]
Thank you for the hint. Updating softcover from 1.1.13 to 1.1.14 fixed the equation number at `softcover_book/html/softcover_markdown.html#eq-golden_ratio` and `http://localhost:4000/softcover_markdown#eq-golden_ratio`. 

However the single page html at `softcover_book/html/softcover_book.html#eq-golden_ratio` still shows the equation number (2) instead of (3.1).

**Comment by mhartl** [comment]
Because of the way MathJax numbers equations, there's no way to get the equation numbers on the single-page view to match those on the chapter views. The single-page view is mainly used internally, though it is exposed for search purposes. Anyone using that view for full-text search will just have to navigate to the corresponding chapter view to see properly numbered equations.

**Comment by asmaier** [comment]
Ok. I just thought because the reference to the equation shows the correct number (3.1) it should be possible to make the equation also show the correct number. But as I understand this is not possible.
